### PR TITLE
[WIP] docs: add authoring template for openshift quick starts

### PR DESCRIPTION
**Pull request by jbyrne-redhat**

### CODE REVIEW

**Comment by jbyrne-redhat** [comment]
@secondsun @wtrocki Just giving this PR a bump. If you get a chance to review, I'd appreciate it. 

Thanks!

**Comment by wtrocki** [comment]
@secondsun any reason why we did not reviewed those changes?

**Comment by secondsun** [comment]
@wtrocki Just the WIP label. Changes look like a good, template for quickstarts. If it is ready to merge I'll merge it

**Comment by wtrocki** [comment]
@jbyrne-redhat Can you add more info why, what and remove WIP label. 

@secondsun I remember that we had concerns to not include that into the official operator templates. 
Would renaming it to _template fix that?

**Comment by secondsun** [comment]
The only problem having the template here is that if someone runs `oc apply -f ./olm/quickstarts` the command would try to install the template. The operator supplies a list of templates to install when it runs.

**Review by wtrocki — APPROVED** [review]

**Comment by jbyrne-redhat** [comment]
> The only problem having the template here is that if someone runs `oc apply -f ./olm/quickstarts` the command would try to install the template. The operator supplies a list of templates to install when it runs.

Ah, OK. I thought we explicitly specified a list of quick starts to be installed with the Operator and therefore this would be exempt. In that case, can I add a `templates` sub-dir and drop it into that?

**Review by wtrocki — APPROVED** [review]

**Pull request merged**
