### PR TITLE
Updates to Custom Resource controller documentation

### PR DESCRIPTION
**Pull request by jbyrne-redhat**
A preview of the rendered HTML is available for review [here](http://file.emea.redhat.com/~jbyrne/gh158/controllers.html)

### CODE REVIEW

**Comment by wtrocki** [comment]
@jbyrne-redhat Amazing changes! thank you so much. I would also ask @secondsun to verify if the original changes are still up to date. You have approval from myself.

**Review by wtrocki — APPROVED** [review]

**Comment by secondsun** [comment]
I'll take a look today.

**Review by secondsun — APPROVED** [review]

**Comment by secondsun** [comment]
LGTM,  can you squash your commits and edit the "Docs" prefix to be lowercase "docs"? This will fix the build error.

**Comment by jbyrne-redhat** [comment]
Thanks @wtrocki and @secondsun.

**Pull request merged**
